### PR TITLE
Make the code a real gem and...

### PR DESCRIPTION
**Pull request by midwire**
- Reworked Scott Bradley's code to use newer RSpec version.
- Added a .gemspec file
- Added my midwire_common gem to automate version:bump tasks
- Added a LICENSE.txt file
- Added this CHANGELOG file
- Added a NOTES.md file
- Added some newer methods and classes for our (RentPath) needs

### CODE REVIEW

**Comment by dsandstrom** [comment]
@scottwb Can this be merged?

**Comment by scottwb** [comment]
@dsandstrom Ah...yes...All of these changes sound great. I haven't been using this gem actively for about 6 months and I've been pretty slammed lately so my time on accepting PRs has unfortunately fallen by the wayside. I will try to look at it within the next week or so.

**Comment by nhocki** [comment]
@scottwb have you had time to take a look at this? If you're busy in other projects and would like some help maintaining this I could help you. I have some paid time at work for open source and I'd love to see this mock maintained.

**Comment by dmur** [comment]
Thanks @midwire, this is helpful! :+1:

**Comment by fredrik** [comment]
Publishing as a gem and collating the various forks is a great step in the right direction. Nice work, @midwire. 

@scottwb, might it be time to hand over the reins to a set of maintainers? @nhocki has offered his services. I also note that @svs has already published a gem from a fork of this repo.

It would be great to keep this project alive. :+1:

**Comment by midwire** [comment]
Is there a proper fork of this yet? I'm getting tired of seeing this PR in my outstanding list (for the last 3 years) but I hesitate to close it until there is a fork from a new maintainer.

**Pull request closed without merging**
